### ISSUE TITLE
Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."

### ISSUE THREAD

**Issue by Juanito99** [Juanito99/Windows.Server.Webservice.LogdirectoryWatcher#1]
User reported:

I got an error on the script on one exchange machine in my testscom:
System.Management.Automation.MethodInvocationException: #Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."At line:113 char:4
+ $webLogDirSizeMB = [double]::Parse(([Math]::Round((( ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
at Microsoft.EnterpriseManagement.Common.PowerShell.RunspaceController.RunScript[T](String scriptName, String scriptBody, Dictionary`2 parameters, Object[] constructorArgs, IScriptDebug iScriptDebug, Boolean bSerializeOutput)

Skriptnamn: MonitorLogDirectoryThreeState.ps1

**Comment by Juanito99** [comment]
Bug fixed by changing [double]::Parse to [double]::TryParse.
